apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  labels:
    app: vault-agent-demo
spec:
  selector:
    matchLabels:
      app: vault-agent-demo
  replicas: 1
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-secret-helloworld: "demo/test"
        vault.hashicorp.com/role: "demoapp"
      labels:
        app: vault-agent-demo
    spec:
      serviceAccountName: demo-app
      containers:
      - name: app
        image: jweissig/app:0.0.1
        volumeMounts:
        - name: test
          mountPath: "/etc/foo"
          readOnly: true
      volumes:
      - name: test
        secret:
          secretName: test-secret
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: demo-app
  labels:
    app: vault-agent-demo
